/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author alexander.brito
 */
public class Form_Banho extends javax.swing.JFrame {

    /**
     * Creates new form Form_Banho
     */
    public Form_Banho() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        painelPrincipal = new javax.swing.JPanel();
        btnAgendar = new javax.swing.JButton();
        comboxDia = new javax.swing.JComboBox<>();
        petCampo = new javax.swing.JTextField();
        PetPessoa = new javax.swing.JLabel();
        dia = new javax.swing.JLabel();
        clienteCampo = new javax.swing.JTextField();
        cliente = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        itemPaginaPrincial = new javax.swing.JMenuItem();
        itemTosa = new javax.swing.JMenuItem();
        itemAgendamento = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPrincipal.setLayout(null);

        btnAgendar.setText("Agendar");
        painelPrincipal.add(btnAgendar);
        btnAgendar.setBounds(290, 150, 73, 23);

        comboxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        painelPrincipal.add(comboxDia);
        comboxDia.setBounds(100, 190, 140, 20);
        painelPrincipal.add(petCampo);
        petCampo.setBounds(100, 150, 140, 20);

        PetPessoa.setText("Pet");
        painelPrincipal.add(PetPessoa);
        PetPessoa.setBounds(60, 150, 40, 20);

        dia.setText("Dia");
        painelPrincipal.add(dia);
        dia.setBounds(60, 190, 40, 20);
        painelPrincipal.add(clienteCampo);
        clienteCampo.setBounds(99, 120, 140, 20);

        cliente.setText("Cliente");
        painelPrincipal.add(cliente);
        cliente.setBounds(60, 120, 40, 20);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banhoetosa1.jpg"))); // NOI18N
        painelPrincipal.add(fundo);
        fundo.setBounds(0, 0, 475, 487);

        Menu.setText("Menu");

        itemPaginaPrincial.setText("Página principal");
        itemPaginaPrincial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPaginaPrincialActionPerformed(evt);
            }
        });
        Menu.add(itemPaginaPrincial);

        itemTosa.setText("Tosa");
        Menu.add(itemTosa);

        itemAgendamento.setText("Agendamentos");
        Menu.add(itemAgendamento);

        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemPaginaPrincialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPaginaPrincialActionPerformed
        // TODO add your handling code here:
        Form_Home home = new Form_Home();
        home.setVisible(true);
        this.setVisible(false);
            
    }//GEN-LAST:event_itemPaginaPrincialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Banho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Banho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Banho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Banho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Banho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JLabel PetPessoa;
    private javax.swing.JButton btnAgendar;
    private javax.swing.JLabel cliente;
    private javax.swing.JTextField clienteCampo;
    private javax.swing.JComboBox<String> comboxDia;
    private javax.swing.JLabel dia;
    private javax.swing.JLabel fundo;
    private javax.swing.JMenuItem itemAgendamento;
    private javax.swing.JMenuItem itemPaginaPrincial;
    private javax.swing.JMenuItem itemTosa;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JTextField petCampo;
    // End of variables declaration//GEN-END:variables
}
