/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author alexander.brito
 */
public class Form_Home extends javax.swing.JFrame {

    /**
     * Creates new form Form_CadEquipamento
     */
    public Form_Home() {
        initComponents();
         this.setLocationRelativeTo(null);
//        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelInicio = new javax.swing.JPanel();
        imgFundo = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        servicos = new javax.swing.JMenu();
        itemBanho = new javax.swing.JMenuItem();
        itemTosa = new javax.swing.JMenuItem();
        itemExames = new javax.swing.JMenuItem();
        itemAgendamentos = new javax.swing.JMenuItem();
        itemPets = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        itemPessoas = new javax.swing.JMenuItem();
        itemFuncionarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Página inicial");

        painelInicio.setName("Home"); // NOI18N

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-cadastro-1.jpg"))); // NOI18N

        javax.swing.GroupLayout painelInicioLayout = new javax.swing.GroupLayout(painelInicio);
        painelInicio.setLayout(painelInicioLayout);
        painelInicioLayout.setHorizontalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgFundo, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        painelInicioLayout.setVerticalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInicioLayout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(imgFundo))
        );

        servicos.setText("Menu");

        itemBanho.setText("banho");
        itemBanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBanhoActionPerformed(evt);
            }
        });
        servicos.add(itemBanho);

        itemTosa.setText("Tosa");
        servicos.add(itemTosa);

        itemExames.setText("Exames");
        servicos.add(itemExames);

        itemAgendamentos.setText("Agendamentos");
        servicos.add(itemAgendamentos);

        itemPets.setText("Pets");
        servicos.add(itemPets);

        jMenuItem2.setText("Cadastro de Pets");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        servicos.add(jMenuItem2);

        itemPessoas.setText("Pessoas");
        servicos.add(itemPessoas);

        itemFuncionarios.setText("Funcionários");
        servicos.add(itemFuncionarios);

        menu.add(servicos);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemBanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBanhoActionPerformed
        // TODO add your handling code here:
        Form_Banho pagBanho = new Form_Banho();
        pagBanho.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemBanhoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Form_CadastroPet  pagCadastroPet = new Form_CadastroPet();
        pagCadastroPet.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFundo;
    private javax.swing.JMenuItem itemAgendamentos;
    private javax.swing.JMenuItem itemBanho;
    private javax.swing.JMenuItem itemExames;
    private javax.swing.JMenuItem itemFuncionarios;
    private javax.swing.JMenuItem itemPessoas;
    private javax.swing.JMenuItem itemPets;
    private javax.swing.JMenuItem itemTosa;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menu;
    private javax.swing.JPanel painelInicio;
    private javax.swing.JMenu servicos;
    // End of variables declaration//GEN-END:variables
}
